---
# /etc/ansible/hosts
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    # created with:
    # openssl passwd -salt tekitou_salt -1 *******
    password: $1$tekitou_salt$Qa8Cdl.FfMfkf.JsiunoM1
  remote_user: root
  tasks:
  - user: name=koromaru password={{password}} shell=/bin/bash createhome=yes state=present append=yes groups=sudo
  - name: ensure python-dev is at the latest version
    apt: pkg=python-dev state=latest
  - name: ensure various packages are at latest version
    apt: pkg=python-virtualenv state=latest
  - name: ensure various packages are at latest version
    apt: pkg=librtmp-dev state=latest
  - name: ensure various packages are at latest version
    apt: pkg=libffi-dev state=latest

- hosts: 127.0.0.1
  connection: local
  vars:
    local_home: /home/koromaru
  become: yes
  become_user: koromaru
  tasks:
  - name: ensure various packages are at latest version
    pip: name=cffi virtualenv={{local_home}}/venv state=latest
  - name: ensure various packages are at latest version
    pip: name=python-librtmp virtualenv={{local_home}}/venv state=latest
  - name: ensure various packages are at latest version
    pip: name=livestreamer virtualenv={{local_home}}/venv state=latest
